### ISSUE TITLE
New for state must be created for links to be more descriptive in their status

### ISSUE THREAD

**Issue by dgarc330** [kytos-ng/topology#14]
Upon reviewing the events generated by the topology napp, we noticed that when we enable a link, the event is generated by the same method that create events for link_up and link_down and therefore, there is no easy way to know if the link was enabled/disabled (administrative) or just flapped (operational) for same reason. As a fix, we think that instead of link_up or link_down, the status should be link_enabled and link_disabled. 

Antonio also suggested that instead of creating new events, we can add a function or a variable within the event object to offer the details and descriptions that we are laking right now to better understand what is the true status and reason behind the status of the links. 

The suggested code for review is the following:

```
def notify_link_status_change(self, link):
        """Send an event to notify about a status change on a link."""
        name = 'kytos/topology.'
        if link.is_active() and link.is_enabled():
            status = 'link_up'
        else:
            status = 'link_down'
        event = KytosEvent(name=name+status, content={'link': link})
        self.controller.buffers.app.put(event)
```

**Comment by italovalcy** [comment]
Thank you, Daniela! I think that adding a new event, along with the existing one, is pretty straightforward. Besides, it will be easier for a Kytos Napp to just listen to a specific new event (e.g., link enabled/disabled) than look at the event's body to see if that is what is needed. @ajoaoff I would like to hear more from you on that matter.

**Comment by ajoaoff** [comment]
I don't know in which case a NApp would have a different behavior when the link is disabled or goes down. `mef_eline` has the same behavior and I don't know if any other NApp listens for those events.
