### ISSUE TITLE
Topology should allow for delete a link

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/topology#154]
Sometimes, during a maintenance window, transient configuration, or general migrations, a Link is created and no longer used (physically removed). Kytos topology should allow the admin/operator to remove such links from the topology. Disabling those links is not enough because the link will keep being displayed on UI (the workaround for this would be only displaying links enabled -- but other components wouldn't benefit from that unless they are changed accordingly).

One suggestion would be having an attribute for archived (defaults to False), and when someone requests a link removal, we save that link with archived=True. Then, when loading links from MongoDB, add a filter to only load archived = False. Also, when adding a new link, we should override possible existing ones (think about a use case where the operator removed the link and later on the link was created again).

Also, when removing the link, we have to be careful to update endpoints (interfaces), specially the `link` attribute and `nni/uni`. Special attention should be given to the case where the same endpoint is now being used to a new link! In this case, we shouldn't reset the endpoint's `link` attribute or even `nni/uni`.

**Comment by viniarck** [comment]
Right, great point, Italo. Indeed, soft deletions sound great for this case. 

Side note: it's partly related to https://github.com/kytos-ng/topology/issues/39, where generically it was discussed to allow deletions, but still at that point we hadn't discussed if only soft deletions or hard deletions, looks like evolving incrementally with soft deletion but just for links should suffice, so, it's also an opportunity to review/discuss if hard deletions should also be included in the scope or not. Let's keep this in mind also when someone is ready to start to implement this one on `2023.2`.

**Comment by italovalcy** [comment]
@viniarck can you please validate if the below sequence of commands can be considered a workaround to be executed in the Kytos console?

```
link_id = "xxxxxxxxxxx"
link = controller.napps[('kytos', 'topology')].links.pop(link_id)

If link == link.endpoint_a.link:
	switch = controller.napps[('kytos', 'topology')].links[link_id].endpoint_a.switch
	controller.napps[('kytos', 'topology')].links[link_id].endpoint_a.link = None
	controller.napps[('kytos', 'topology')].links[link_id].endpoint_a.nni = False
	controller.napps[('kytos', 'topology')].topo_controller.upsert_switch(switch.id, switch.as_dict())


If link == link.endpoint_b.link:
	switch = controller.napps[('kytos', 'topology')].links[link_id].endpoint_b.switch
	controller.napps[('kytos', 'topology')].links[link_id].endpoint_b.link = None
	controller.napps[('kytos', 'topology')].links[link_id].endpoint_b.nni = False
	controller.napps[('kytos', 'topology')].topo_controller.upsert_switch(switch.id, switch.as_dict())


controller.napps[('kytos', 'topology')].topo_controller.db.links.find_one_and_delete({"_id": link.id})
```

**Comment by viniarck** [comment]
@italovalcy it mostly is, I added a lock to be extra safe, and then we also need to call `notify_topology_update()` just so the current graph can be published, check out this script:

```python
# link between s1-eth3 and s3-eth4 on extra linear,4 topology,
link_id = "da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b"
topology = controller.napps[("kytos", "topology")]
link = topology.links[link_id]

with topology._links_lock:
    if link == link.endpoint_a.link:
        print(f"processing link endpoint_a {link.endpoint_a}")
        switch = topology.links[link_id].endpoint_a.switch
        topology.links[link_id].endpoint_a.link = None
        topology.links[link_id].endpoint_a.nni = False
        topology.topo_controller.upsert_switch(switch.id, switch.as_dict())

    if link == link.endpoint_b.link:
        print(f"processing link endpoint_b {link.endpoint_b}")
        switch = topology.links[link_id].endpoint_b.switch
        topology.links[link_id].endpoint_b.link = None
        topology.links[link_id].endpoint_b.nni = False
        topology.topo_controller.upsert_switch(switch.id, switch.as_dict())

    link = topology.links.pop(link_id)
    deleted_link = topology.topo_controller.db.links.find_one_and_delete(
        {"_id": link.id}
    )
    print(f"deleted {deleted_link}")
    topology.notify_topology_update()

```

- Before the deletion I confirmed that `pathfinder` had 2 paths from s1 to s4:

```
❯ curl -s -X POST -H 'Content-type: application/json' http://127.0.0.1:8181/api/kytos/pathfinder/v3/ -d '{"source": "00:00:00:00:00:00:00:01:1", "destination":  "00:00:00:00:00:00:00:04
:1"}' | jq -r
{
  "paths": [
    {
      "hops": [
        "00:00:00:00:00:00:00:01:1",
        "00:00:00:00:00:00:00:01",
        "00:00:00:00:00:00:00:01:3",
        "00:00:00:00:00:00:00:03:4",
        "00:00:00:00:00:00:00:03",
        "00:00:00:00:00:00:00:03:3",
        "00:00:00:00:00:00:00:04:2",
        "00:00:00:00:00:00:00:04",
        "00:00:00:00:00:00:00:04:1"
      ],
      "cost": 8
    },
    {
      "hops": [
        "00:00:00:00:00:00:00:01:1",
        "00:00:00:00:00:00:00:01",
        "00:00:00:00:00:00:00:01:2",
        "00:00:00:00:00:00:00:02:2",
        "00:00:00:00:00:00:00:02",
        "00:00:00:00:00:00:00:02:3",
        "00:00:00:00:00:00:00:03:2",
        "00:00:00:00:00:00:00:03",
        "00:00:00:00:00:00:00:03:3",
        "00:00:00:00:00:00:00:04:2",
        "00:00:00:00:00:00:00:04",
        "00:00:00:00:00:00:00:04:1"
      ],
      "cost": 11
    }
  ]
}

```

I tested it on a `linear,4` topology with an extra link:

```
kytos $> link_id = "da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b" 
    ...: topology = controller.napps[("kytos", "topology")] 
    ...: link = topology.links[link_id] 
    ...:  
    ...: with topology._links_lock: 
    ...:     if link == link.endpoint_a.link: 
    ...:         print(f"processing link endpoint_a {link.endpoint_a}") 
    ...:         switch = topology.links[link_id].endpoint_a.switch 
    ...:         topology.links[link_id].endpoint_a.link = None 
    ...:         topology.links[link_id].endpoint_a.nni = False 
    ...:         topology.topo_controller.upsert_switch(switch.id, switch.as_dict()) 
    ...:  
    ...:     if link == link.endpoint_b.link: 
    ...:         print(f"processing link endpoint_b {link.endpoint_b}") 
    ...:         switch = topology.links[link_id].endpoint_b.switch 
    ...:         topology.links[link_id].endpoint_b.link = None 
    ...:         topology.links[link_id].endpoint_b.nni = False 
    ...:         topology.topo_controller.upsert_switch(switch.id, switch.as_dict()) 
    ...:  
    ...:     link = topology.links.pop(link_id) 
    ...:     deleted_link = topology.topo_controller.db.links.find_one_and_delete( 
    ...:         {"_id": link.id} 
    ...:     ) 
    ...:     print(f"deleted {deleted_link}") 
    ...:     topology.notify_topology_update() 
    ...:                                                                                                                                                                                 
processing link endpoint_a Interface('s1-eth3', 3, Switch('00:00:00:00:00:00:00:01'))
processing link endpoint_b Interface('s3-eth4', 4, Switch('00:00:00:00:00:00:00:03'))
deleted {'_id': 'da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b', 'enabled': True, 'endpoints': [{'id': '00:00:00:00:00:00:00:01:3'}, {'id': '00:00:00:00:00:00:00:03:4
'}], 'id': 'da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b', 'inserted_at': datetime.datetime(2023, 7, 20, 21, 14, 32, 487000), 'metadata': {'last_status_change': 1689
887672.4871647, 'last_status_is_active': True}, 'updated_at': datetime.datetime(2023, 7, 20, 21, 14, 32, 487000)}

```

- After that I re-ran pathfinder request:

```
❯ curl -s -X POST -H 'Content-type: application/json' http://127.0.0.1:8181/api/kytos/pathfinder/v3/ -d '{"source": "00:00:00:00:00:00:00:01:1", "destination":  "00:00:00:00:00:00:00:04
:1"}' | jq -r
{
  "paths": [
    {
      "hops": [
        "00:00:00:00:00:00:00:01:1",
        "00:00:00:00:00:00:00:01",
        "00:00:00:00:00:00:00:01:2",
        "00:00:00:00:00:00:00:02:2",
        "00:00:00:00:00:00:00:02",
        "00:00:00:00:00:00:00:02:3",
        "00:00:00:00:00:00:00:03:2",
        "00:00:00:00:00:00:00:03",
        "00:00:00:00:00:00:00:03:3",
        "00:00:00:00:00:00:00:04:2",
        "00:00:00:00:00:00:00:04",
        "00:00:00:00:00:00:00:04:1"
      ],
      "cost": 11
    }
  ]
}
```

I also restarted, `kytosd` make a request to topology and pathfinder again, and no errors showed up, DB documents as expected too.

**Comment by italovalcy** [comment]
> @italovalcy it mostly is, I added a lock to be extra safe, and then we also need to call `notify_topology_update()` just so the current graph can be published, check out this script:
> 
> ```python
> # link between s1-eth3 and s3-eth4 on extra linear,4 topology,
> link_id = "da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b"
> topology = controller.napps[("kytos", "topology")]
> link = topology.links[link_id]
> 
> with topology._links_lock:
>     if link == link.endpoint_a.link:
>         print(f"processing link endpoint_a {link.endpoint_a}")
>         switch = topology.links[link_id].endpoint_a.switch
>         topology.links[link_id].endpoint_a.link = None
>         topology.links[link_id].endpoint_a.nni = False
>         topology.topo_controller.upsert_switch(switch.id, switch.as_dict())
> 
>     if link == link.endpoint_b.link:
>         print(f"processing link endpoint_b {link.endpoint_b}")
>         switch = topology.links[link_id].endpoint_b.switch
>         topology.links[link_id].endpoint_b.link = None
>         topology.links[link_id].endpoint_b.nni = False
>         topology.topo_controller.upsert_switch(switch.id, switch.as_dict())
> 
>     link = topology.links.pop(link_id)
>     deleted_link = topology.topo_controller.db.links.find_one_and_delete(
>         {"_id": link.id}
>     )
>     print(f"deleted {deleted_link}")
>     topology.notify_topology_update()
> ```
> 
>  * Before the deletion I confirmed that `pathfinder` had 2 paths from s1 to s4:
> 
> ```
> ❯ curl -s -X POST -H 'Content-type: application/json' http://127.0.0.1:8181/api/kytos/pathfinder/v3/ -d '{"source": "00:00:00:00:00:00:00:01:1", "destination":  "00:00:00:00:00:00:00:04
> :1"}' | jq -r
> {
>   "paths": [
>     {
>       "hops": [
>         "00:00:00:00:00:00:00:01:1",
>         "00:00:00:00:00:00:00:01",
>         "00:00:00:00:00:00:00:01:3",
>         "00:00:00:00:00:00:00:03:4",
>         "00:00:00:00:00:00:00:03",
>         "00:00:00:00:00:00:00:03:3",
>         "00:00:00:00:00:00:00:04:2",
>         "00:00:00:00:00:00:00:04",
>         "00:00:00:00:00:00:00:04:1"
>       ],
>       "cost": 8
>     },
>     {
>       "hops": [
>         "00:00:00:00:00:00:00:01:1",
>         "00:00:00:00:00:00:00:01",
>         "00:00:00:00:00:00:00:01:2",
>         "00:00:00:00:00:00:00:02:2",
>         "00:00:00:00:00:00:00:02",
>         "00:00:00:00:00:00:00:02:3",
>         "00:00:00:00:00:00:00:03:2",
>         "00:00:00:00:00:00:00:03",
>         "00:00:00:00:00:00:00:03:3",
>         "00:00:00:00:00:00:00:04:2",
>         "00:00:00:00:00:00:00:04",
>         "00:00:00:00:00:00:00:04:1"
>       ],
>       "cost": 11
>     }
>   ]
> }
> ```
> 
> I tested it on a `linear,4` topology with an extra link:
> 
> ```
> kytos $> link_id = "da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b" 
>     ...: topology = controller.napps[("kytos", "topology")] 
>     ...: link = topology.links[link_id] 
>     ...:  
>     ...: with topology._links_lock: 
>     ...:     if link == link.endpoint_a.link: 
>     ...:         print(f"processing link endpoint_a {link.endpoint_a}") 
>     ...:         switch = topology.links[link_id].endpoint_a.switch 
>     ...:         topology.links[link_id].endpoint_a.link = None 
>     ...:         topology.links[link_id].endpoint_a.nni = False 
>     ...:         topology.topo_controller.upsert_switch(switch.id, switch.as_dict()) 
>     ...:  
>     ...:     if link == link.endpoint_b.link: 
>     ...:         print(f"processing link endpoint_b {link.endpoint_b}") 
>     ...:         switch = topology.links[link_id].endpoint_b.switch 
>     ...:         topology.links[link_id].endpoint_b.link = None 
>     ...:         topology.links[link_id].endpoint_b.nni = False 
>     ...:         topology.topo_controller.upsert_switch(switch.id, switch.as_dict()) 
>     ...:  
>     ...:     link = topology.links.pop(link_id) 
>     ...:     deleted_link = topology.topo_controller.db.links.find_one_and_delete( 
>     ...:         {"_id": link.id} 
>     ...:     ) 
>     ...:     print(f"deleted {deleted_link}") 
>     ...:     topology.notify_topology_update() 
>     ...:                                                                                                                                                                                 
> processing link endpoint_a Interface('s1-eth3', 3, Switch('00:00:00:00:00:00:00:01'))
> processing link endpoint_b Interface('s3-eth4', 4, Switch('00:00:00:00:00:00:00:03'))
> deleted {'_id': 'da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b', 'enabled': True, 'endpoints': [{'id': '00:00:00:00:00:00:00:01:3'}, {'id': '00:00:00:00:00:00:00:03:4
> '}], 'id': 'da6b96a17fa20dbcbcf989a7b9d915cc4b81dea177324499f4e692e455b6aa8b', 'inserted_at': datetime.datetime(2023, 7, 20, 21, 14, 32, 487000), 'metadata': {'last_status_change': 1689
> 887672.4871647, 'last_status_is_active': True}, 'updated_at': datetime.datetime(2023, 7, 20, 21, 14, 32, 487000)}
> ```
> 
>  * After that I re-ran pathfinder request:
> 
> ```
> ❯ curl -s -X POST -H 'Content-type: application/json' http://127.0.0.1:8181/api/kytos/pathfinder/v3/ -d '{"source": "00:00:00:00:00:00:00:01:1", "destination":  "00:00:00:00:00:00:00:04
> :1"}' | jq -r
> {
>   "paths": [
>     {
>       "hops": [
>         "00:00:00:00:00:00:00:01:1",
>         "00:00:00:00:00:00:00:01",
>         "00:00:00:00:00:00:00:01:2",
>         "00:00:00:00:00:00:00:02:2",
>         "00:00:00:00:00:00:00:02",
>         "00:00:00:00:00:00:00:02:3",
>         "00:00:00:00:00:00:00:03:2",
>         "00:00:00:00:00:00:00:03",
>         "00:00:00:00:00:00:00:03:3",
>         "00:00:00:00:00:00:00:04:2",
>         "00:00:00:00:00:00:00:04",
>         "00:00:00:00:00:00:00:04:1"
>       ],
>       "cost": 11
>     }
>   ]
> }
> ```
> 
> I also restarted, `kytosd` make a request to topology and pathfinder again, and no errors showed up, DB documents as expected too.

great!! thanks a lot for your input on this, Vinicius!

**Comment by italovalcy** [comment]
@viniarck, here is an updated version to handle a corner case when the link os resulting of an interface loop (example: port 19 connected to port 19)

```
topology = controller.napps[("kytos", "topology")]
link = topology.links[link_id]

with topology._links_lock:
    if link.endpoint_a.link and link == link.endpoint_a.link:
        print(f"processing link endpoint_a {link.endpoint_a}")
        switch = topology.links[link_id].endpoint_a.switch
        topology.links[link_id].endpoint_a.link = None
        topology.links[link_id].endpoint_a.nni = False
        topology.topo_controller.upsert_switch(switch.id, switch.as_dict())

    if link.endpoint_b.link and link == link.endpoint_b.link:
        print(f"processing link endpoint_b {link.endpoint_b}")
        switch = topology.links[link_id].endpoint_b.switch
        topology.links[link_id].endpoint_b.link = None
        topology.links[link_id].endpoint_b.nni = False
        topology.topo_controller.upsert_switch(switch.id, switch.as_dict())

    link = topology.links.pop(link_id)
    deleted_link = topology.topo_controller.db.links.find_one_and_delete(
        {"_id": link.id}
    )
    print(f"deleted {deleted_link}")
    topology.notify_topology_update()
```

**Comment by Alopalao** [comment]
Looks like soft deletions makes more sense for links right now. To achieve this it is required two new endpoints `POST` and `DELETE` to add/delete a link. These endpoints will change `archived` value as well as enable/disable the link. Am I missing something?

**Comment by viniarck** [comment]
> Looks like soft deletions makes more sense for links right now. To achieve this it is required two new endpoints `POST` and `DELETE` to add/delete a link. These endpoints will change `archived` value as well as enable/disable the link. Am I missing something?

After thinking more about it, and also considering holistically how other entities (like interface and switches can get deleted) I'm inclined that hard deletions are more suited and easier to maintain. I mean, inherently the platform relies on entities discovery (or resource creation), and we do already provide the enable/disable control, so to also try to control when a soft deleted entity gets discovery again it would require more extra control, and since the point of deletion is indeed when no longer a network operators wants to deal with a particular network entity, then a hard deletion would easier to maintain and integrate and coexist well with enable/disable.

Unless we would like to also even avoid that soft deleted entities get ever discovered or reconnected again, which isn't the case as far as based on what's discussed. @italovalcy and @Alopalao let me know if you agree that we can move forward with hard deletions instead. 

> To achieve this it is required two new endpoints POST and DELETE to add/delete a link.

I'd say only a `DELETE` endpoint, currently we do not manual resource creation since the southbound works based on resource discovery (and/or recovery creation based on the protocol message contents), forcing a link (or any other entity) creation can lead to surprises and not synced with the underlying network topology. 

>  value as well as enable/disable the link.

If we move forward with hard deletions this no longer will be the case, notice that with soft deletions it's already blurring its responsibility with enable/disable.
