### ISSUE TITLE
Start to use `pool="dynamic_single"` to ensure FIFO event processing on interruptions

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/topology#155]
Currently, [`on_interruption_start`](https://github.com/kytos-ng/topology/blob/master/main.py#L1070) and [`on_interruption_end`](https://github.com/kytos-ng/topology/blob/master/main.py#L1106) handlers are both running on the default `app` pool, they have a lock protection, but still it's vulnerable to out of order events, depending on the frequency this can happen. 

These two handlers could be refactored in a single using a `dynamic_single` pool that will be shipped on this PR https://github.com/kytos-ng/kytos/pull/399, and then branch from here processing each start and end accordingly, these handlers don't deal wit blocking IO, it can utilize the `dynamic_single`:

```
    @listen_to('topology.interruption.*', pool="dynamic_single")
    def on_interruption(self, event: KytosEvent):
        ...
```

Ideally, this needs to be done before liveness start to use interruptions cc'ing @Ktmi for his information

**Comment by Ktmi** [comment]
Yeah, we can go this route. In fact it would probably help simplify the logic in a few places. I just have one question; are each of the listeners a separate thread, or does one thread from the pool execute each listener?
