### ISSUE TITLE
Topology should allow delete a switch

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/topology#164]
Similar to Issue #154, it would be nice if we have ways to delete a switch from Kytos-ng (topology/database). After some migration/maintenance window, you may end up with a switch on the topology that is not active anymore and will never connect again.

We should then:
 - Delete the switch from `controller.switches`
 - Delete the switch and its interfaces from MongoDB topology collections
 - Delete flows that are associated with that switch?

Before all of this, we should make sure the switch is not being used for any service? Mef_eline, flows, etc? Provide means to force removal (even if it is being used by EVCs? Flows?)?

**Comment by Alopalao** [comment]
EVCs related to the soon-to-be-deleted switch should be deleted. An exception will be raised while creating a UNI object.

> Provide means to force removal (even if it is being used by EVCs? Flows?)?

Seems doable. Recognizing EVC-created flows can be done by looking at `"flow.owner"` in each flow. `mef_eline` can delete EVCs that are related to the deleted switch. It can be `kytos/topology.switch_deleted`  the event that notifies other NApps. On the other hand, the EVC deletions could be done by the user as well.

> Delete flows that are associated with that switch?

Taking into account that EVC flows are going to be deleted. `coloring` is the one currently not capable of deleting flows. And, we have the same case with deleting flows.

To recognize a disconnected switch, is it enough to look into `status == EntityStatus.DISABLED`?
