### ISSUE TITLE
Interfaces are removed from topology when switch disconnects

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/topology#20]
When the switch disconnects from kytos, all interfaces are removed, except the OFPP_LOCAL interface. Since the switches are preserved in the topology with active=False, the OFPP_LOCAL is also preserved, and the topology is loaded at kytos startup (with active=False if the switches are not connected yet), it does not make sense the observed behavior.

How to reproduce:
1. start mininet and kytos
2. check that all interfaces and switches are listed in the topology
3. shutdown mininet
4. check the topology again

Expected behavior: switches and interfaces should be listed, but with active=False

Actual behavior: switches are listed as active=False, interfaces are removed (except the OFPP_LOCAL)

**Comment by italovalcy** [comment]
Discussing with @viniarck about this approach of not removing interfaces (which is impacting Issue #34),  he highlighted that special attention should be given to logical interfaces, to avoid keep them forever referred in the switch. In the other hand, removing a legitime Interface when switch disconnects would break references in other places like EVCs, Links, etc. (the issue #34 is an example of broken reference to an endpoint due its removal and creation in a switch reconnection event).

An way to deals with such scenario is:
1. Not automatically remove the interface when receiving a OFPPR_DELETE message, but just change its state to inactive
2. Provide means (APIs) so the operator can remove a specific inactive interface, or all inactive interface
3. Provide means (configuration) so the operator can enable a "house keeping / cleanup" routine which removes interfaces that are inactive for a while (e.g., remove all interfaces inactive for more than 30 days)

**Comment by viniarck** [comment]
> Discussing with @viniarck about this approach of not removing interfaces (which is impacting Issue #34), he highlighted that special attention should be given to logical interfaces, to avoid keep them forever referred in the switch. In the other hand, removing a legitime Interface when switch disconnects would break references in other places like EVCs, Links, etc. (the issue #34 is an example of broken reference to an endpoint due its removal and creation in a switch reconnection event).
> 
> An way to deals with such scenario is:
> 
> 1. Not automatically remove the interface when receiving a OFPPR_DELETE message, but just change its state to inactive
> 2. Provide means (APIs) so the operator can remove a specific inactive interface, or all inactive interface
> 3. Provide means (configuration) so the operator can enable a "house keeping / cleanup" routine which removes interfaces that are inactive for a while (e.g., remove all interfaces inactive for more than 30 days)

Great suggestions and thanks for brainstorming, helping out and mapping this. Sound good to me. I was also double checking, the link is also supposed to be deactivated in this case, but we already had this specific part covered on `topology` https://github.com/kytos-ng/topology/blob/fix/issue_35/main.py#L683-L686.

**Comment by viniarck** [comment]
Closing this issue since this it's been fixed on this PR https://github.com/kytos-ng/of_core/pull/42, the rest of the requirements number 2 and 3 will be addressed on issue #39
