### ISSUE TITLE
ui: enabling or disable links/switches should ask for confirmation

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/topology#202]
Hi,

I thought we had open this issue before, but I didn't manage to find the issue. We had cases in production in which people disabled a switch by accident and that created a lot of impact.

Thus, it would be nice to have a feature that asks for confirmation when enabling/disabling switches/interfaces/links.

**Comment by viniarck** [comment]
I've just labeled it with `future_release` to next in the radar list.

**Comment by viniarck** [comment]
A pop up modal similar to what's been used for switch deletion confirmation can meet this requirement you asked:

![20240523_103901](https://github.com/kytos-ng/topology/assets/1010796/447300ff-2368-4969-8f71-b38c51bc458b)
