### ISSUE TITLE
Memory and database not matching interface `available_tags` values

### ISSUE THREAD

**Issue by Alopalao** [kytos-ng/topology#205]
While creating 160 EVCs (80 request at a time), the database did not have the same `available_tags` as what I had in memory.
#### From memory:
```
kytos $> controller.switches['00:00:00:00:00:00:00:01'].interfaces[4].available_tags
Out[2]: {'vlan': [[161, 4095]]}
```
#### From database
```
    _id: '00:00:00:00:00:00:00:01:4',
    available_tags: { vlan: [ [ 160, 4095 ] ] },
    id: '00:00:00:00:00:00:00:01:4',
    inserted_at: ISODate('2024-08-05T15:52:37.062Z'),
    special_available_tags: { vlan: [ 'untagged', 'any' ] },
    special_tags: { vlan: [ 'untagged', 'any' ] },
    tag_ranges: { vlan: [ [ 1, 4095 ] ] },
    updated_at: ISODate('2024-08-05T15:53:01.050Z')
```
I  have only seen this issue happen once. It was found when only EVC creation was performed. Another modification for VLANs would hide this issue.
This interface was part of `failover_path` for all EVCs and it was an NNI (from RingTopo).

Edit:
I am working with a modified mef_eline which could be the cause of the problem. Although at second glance these changes should not affect the process of reporting/using VLANs

Edit2:
It also appears in master branch. I see that the values in memory are correct. This issue can be symptom of duplicated flows if kytos is restarted and then an EVC is created with the missing VLANs.

**Comment by viniarck** [comment]
Good finding @Alopalao, I've temporarily set the target `2024.1` just in case to show up in our issues filter. If it's confirmed that it was just the modified local changes then it's OK and can get closed, otherwise we can reassess if it needs to be fixed.

**Comment by Alopalao** [comment]
I got this error again. Seems to be a problem with MongoDB. I added a log in between the [lines](https://github.com/kytos-ng/topology/blob/d9395127f624dd9b269d9f4c8a2237baef547787/controllers/__init__.py#L323-L324), `log.info(f"From mongo {id_}: {updated['available_tags']}")`. It should be printing the last mongo updated dictionary.

```
2024-08-06 17:26:57,096 - INFO [kytos.napps.kytos/topology] (thread_pool_app_153) From mongo 00:00:00:00:00:00:00:02:3: {'vlan': [[158, 4095]]}
2024-08-06 17:26:57,125 - INFO [kytos.napps.kytos/topology] (thread_pool_app_191) From mongo 00:00:00:00:00:00:00:02:3: {'vlan': [[156, 4095]]}
2024-08-06 17:26:57,229 - INFO [kytos.napps.kytos/topology] (thread_pool_app_173) From mongo 00:00:00:00:00:00:00:02:3: {'vlan': [[160, 4095]]}
2024-08-06 17:26:57,269 - INFO [kytos.napps.kytos/topology] (thread_pool_app_58) From mongo 00:00:00:00:00:00:00:02:3: {'vlan': [[2, 2], [160, 4095]]}
2024-08-06 17:26:57,328 - INFO [kytos.napps.kytos/topology] (thread_pool_app_22) From mongo 00:00:00:00:00:00:00:02:3: {'vlan': [[160, 4095]]}
2024-08-06 17:26:57,340 - INFO [kytos.napps.kytos/topology] (thread_pool_app_62) From mongo 00:00:00:00:00:00:00:02:3: {'vlan': [[161, 4095]]}
```

The last log has the VLAN list `[[161, 4095]]` but the database was not updated:

```
  {
    _id: '00:00:00:00:00:00:00:02:3',
    available_tags: { vlan: [ [ 160, 4095 ] ] },
    id: '00:00:00:00:00:00:00:02:3',
    inserted_at: ISODate('2024-08-06T21:26:29.048Z'),
    special_available_tags: { vlan: [ 'untagged', 'any' ] },
    special_tags: { vlan: [ 'untagged', 'any' ] },
    tag_ranges: { vlan: [ [ 1, 4095 ] ] },
    updated_at: ISODate('2024-08-06T21:26:57.095Z')
  },
```

It may be worth to stress test the sending of `kytos/core.interface_tags` which triggers the upsert of `interface_details`.

**Comment by viniarck** [comment]
Aldo, yes, it needs further investigation. Is it still reproducing without the local changes too, or you don't know yet? 

I was also reviewing, we do have [event out of order protection there too](https://github.com/kytos-ng/topology/blob/master/main.py#L886-L894), but that only works if the events themselves are guaranteed to have being produced in order too, since it's based on its `timestamp` creation attribute. If you're not seeing the write happen in the DB, add a log to see if it's discarding. If it's discarding what's not supposed to, then we'll need to fix/review and ensure that the producer of this event on kytos core to ensure it produces in order too. 

It's still possible that a thread get preempted right on this line [here too](https://github.com/kytos-ng/topology/blob/master/main.py#L894), although MongoDB ensures thread safety for `find_one_and_update`, but let's go by parts here and see if anything is getting discarded first. In the worst case we can also extend the scope of the lock.

**Comment by Alopalao** [comment]
I tried in local changes but it did not appeared. Trying to figure out how my changes can make this issue occurred at the moment.

**Comment by viniarck** [comment]
> ~I tried in local changes but it did not appeared~. Trying to figure out how my changes can make this issue occurred at the moment.
> 
> Edit: It finally did appeared in master branch. This time was with interface `01:1` which was a UNI. I did not check if it was rejected.

OK. If it's happening on `master` it's a bug then. I've set the `bug` label, and `priority_major`. We'll discuss about it in the next meeting. If you can find out if it was rejected or discarded the event that's very helpful.

**Comment by Alopalao** [comment]
Something extra I noticed is that when this issue appeared, `failover_path` of a deployed EVC was set two times by consistency check. These two issues seemed not to be related since mongo logs showed a mismatch with the end values in the DB.
The second deployment of the `failover_path` occurs in `circuit.try_setup_failover_path()` from `execute_consistency()`

**Comment by Alopalao** [comment]
To duplicate this issue with a high rate of success is to add this method inside the class `Interface`:
```
    def testing3(self, controller, n):
        for i in range(n):
            self.available_tags = {"vlan": [[i, 4095]]}
            self._notify_interface_tags(controller)
```

And this can be called from kytos console preferably with a high value number:
```
controller.switches['00:00:00:00:00:00:00:01'].interfaces[1].testing3(controller, 200)
```
Also, only works after a kytos shutdown.

Moving this [line](https://github.com/kytos-ng/topology/blob/c5007784910529dc46bc1910b329b4ef16722a53/main.py#L894) to be inside the lock solves the issue.
