### ISSUE TITLE
`handle_switch_maintenance_end` is assuming interface(s) will go up when maintenance ends

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/topology#62]
[`handle_switch_maintenance_end method`](https://github.com/kytos-ng/topology/blob/master/main.py#L678-L686) is assuming interface(s) will go up when maintenance ends, and also it's setting switch.activate(), but this isn't necessarily safe and the `_active` attribute should be set based on our southbound protocol status information, otherwise it might get out of sync, and lead to inconsistencies. For instance, imagine a switch  maintenance where a network operator is planning to switch replace a physical sfp of an interface, if it gets replaced but then the new sfp doesn't work for some reason, then we'd end up in an inconsistent state in the topology. 

## How to reproduce

- Start mininet: `sudo mn -c && sudo mn --controller=remote,ip=127.0.0.1,port=6653 --switch=ovsk,protocols=OpenFlow13 --topo=linear,3`
- Create a maintenance window `POST {{baseUrl}}/api/kytos/maintenance/`, adapt the start and end time below:

```
{
    "id": "some_mw",
    "description": "some_mw",
    "start": "2022-02-07T14:37:01-0300",
    "end": "2022-02-07T14:38:01-0300",
    "items": [
        "{{dpid}}"
    ]
}
```

- When the maintenance start, simulate that you'll have this interface `s1-eth2` going down: `sudo ip link set dev s1-eth2 down`

- When the maintenance ends, notice in the topology that despite physical low layer down, it'll still be `enabled: true`, and `active: true`

```
❯ ip link show s1-eth2
125: s1-eth2@s2-eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue master ovs-system state DOWN mode DEFAULT group default qlen 1000
    link/ether ca:70:62:f1:47:19 brd ff:ff:ff:ff:ff:ff


{
    "interfaces": {
        "00:00:00:00:00:00:00:01:2": {
            "active": true,
            "enabled": true,
        ....
        }
 }      
 ```

**Comment by Ktmi** [comment]
Fixed with #147
