### ISSUE TITLE
`handle_link_maintenance_start` is using new `Link`s references that don't exist on `self.links`

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/topology#64]
[`handle_link_maintenance_start`](https://github.com/kytos-ng/topology/blob/master/main.py#L1001) is using `Link` instance references that don't exist on topology `self.links`, as a result trying to disable then would lead to inconsistency in the graph since `topology` owns the `self.links` when building the topology and publishing it to subscribers. I think `maintenance` should consume the disable rest endpoint, and then we could also parametrize the `reason`, and rely on `topology` to change accordingly the admin status of link and notify the subscribers, that way having this responsibility in a single place. We might also need to support a list of items to perform a single call.

**Comment by Ktmi** [comment]
Fixed with #147
