### ISSUE TITLE
Trying to enable an interface of a disable switch should return HTTP 409

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/topology#77]
Currently, this endpoint `POST /api/kytos/topology/v3/interfaces/{{ifid}}/enable`, returns 200 and enables a interface even if a switch is disabled, which is inconsistent considering that interfaces belong to a switch, so it should return 409 in that case.

**Comment by Alopalao** [comment]
While working in implementing the new event `kytos/topology.link.enabled/disabled`, this issue needs to be addressed.
